Price_Tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("basic_app.urls")),
    path('admin/', admin.site.urls),
]

basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("saved/", views.saved, name="saved"),
]

basic_app/models.py
from django.db import models

# Create your models here.
class Product(models.Model):

    product_name = models.CharField(max_length=100)
    product_url = models.URLField()
    target_price = models.PositiveIntegerField()
    your_email = models.EmailField()

    def __str__(self):
        return self.product_name;

basic_app/forms.py
from django import forms
from basic_app.models import Product


class ProductForm(forms.ModelForm):
    class Meta():
        model = Product
        fields = "__all__"

basic_app/views.py
from django.shortcuts import render, redirect
from basic_app.forms import ProductForm
from django.contrib import messages
from firebase import firebase

import requests
from bs4 import BeautifulSoup


# Create your views here.
def saved(request):
    return render(request, "basic_app/saved.html", {})

def index(request):
    if request.POST:
        form = ProductForm(request.POST)
        if form.is_valid() and prod_valid(request.POST["product_url"]):
            # form.save()
            save_to_fb(request.POST)
            return redirect("/saved/")
        else:
            messages.info(request, "Invalid Product Link !")
            return redirect("/")
    else:
        form = ProductForm()
        return render(request, "basic_app/index.html", {"form":form})


def save_to_fb(data_dict):
    fb = firebase.FirebaseApplication("https://barcode-scanner-92b37.firebaseio.com/", None)
    data = {
        "product_name" : data_dict["product_name"],
        "product_url" : data_dict["product_url"],
        "target_price" : data_dict["target_price"],
        "your_email" : data_dict["your_email"]
    }

    fb.post("/Products/", data)
    print("saved data !!")

def prod_valid(url):
    USER_AGENTS = [
    ('Mozilla/5.0 (X11; Linux x86_64) '
                     'AppleWebKit/537.36 (KHTML, like Gecko) '
                     'Chrome/57.0.2987.110 '
                     'Safari/537.36'),  # chrome
                    ('Mozilla/5.0 (X11; Linux x86_64) '
                     'AppleWebKit/537.36 (KHTML, like Gecko) '
                     'Chrome/61.0.3163.79 '
                     'Safari/537.36'),  # chrome
                    ('Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) '
                     'Gecko/20100101 '
                     'Firefox/55.0'),  # firefox
                    ('Mozilla/5.0 (X11; Linux x86_64) '
                     'AppleWebKit/537.36 (KHTML, like Gecko) '
                     'Chrome/61.0.3163.91 '
                     'Safari/537.36'),  # chrome
                    ('Mozilla/5.0 (X11; Linux x86_64) '
                     'AppleWebKit/537.36 (KHTML, like Gecko) '
                     'Chrome/62.0.3202.89 '
                     'Safari/537.36'),  # chrome
                    ('Mozilla/5.0 (X11; Linux x86_64) '
                     'AppleWebKit/537.36 (KHTML, like Gecko) '
                     'Chrome/63.0.3239.108 '
                     'Safari/537.36'),
                    ('Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'), ]

    for u in USER_AGENTS:
        HEADERS = {"User-Agent" : u}
        data = requests.get(url, headers=HEADERS).text
        soup = BeautifulSoup(data, "html.parser")

        title_item = soup.find(id="productTitle")
        title = ""

        if title_item:
            title = title_item.get_text().strip()
            return len(title) > 0

    return 0


###############################################

templates/basic_app/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Price Tracker</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "css/helper.css" %}">
</head>

<body class="jumbotron">

  <div class="container text-center">
    <h2><u>Amazon Product Tracker</u></h2>
    <small class="text-center mt-3 form-text text-muted">Enter your product's URL and we'll notify you anytime that item is available at target-price.</small>
    <!-- <h6 class="text-center text-small">Enter your product's URL and we'll notify you anytime that item is available at target-price.</h6> -->

    <div class="jumbotron mx-auto text-center">
      <form method="post" class="text-justify" autocomplete="off">
        <h4>Enter product details :</h4><hr>

        <div class="form-group" autocomplete="off">
          {% csrf_token %}
          <label>Enter Product Name :</label><br>
          {{ form.product_name }}<br><br>

          <label>Product's Amazon Link :</label><br>
          {{ form.product_url }}<br><br>

          <label>Enter Target Price :</label><br>
          {{ form.target_price }}<br><br>

          <label>Enter Your Email :</label><br>
          {{ form.your_email }}<br>
          <small class="form-text text-muted">
            <i class="fa fa-lock" style="color:#007BFF;"></i>
              We do not share your email with anyone else.
          </small>
        </div>
        <input type="submit" value="Submit" class="btn btn-primary"><br>
      </form><hr>

      <div class="text-left">
        {% for m in messages %}
          <h4>{{ m }}</h4>
        {% endfor %}
      </div>

    </div>
  </div>

  </body>
</html>

templates/basic_app/saved.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Saved</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>

    <div class="jumbotron text-center m-5">
      <h2>Your Product is Saved !</h2>
      <br><br>
      <h5>You will be notified when your triggered price is reached.</h5>
      <br><br>
      <a href="{% url 'basic_app:index' %}" class="btn btn-outline-primary btn-lg">Set Another...</a>
    </div>

  </body>
</html>